### ISSUE TITLE
Validate against organizations

### ISSUE THREAD

**Issue by CentaurWarchief** [vincaeco/commitrace-api#9]
Since GitHub organizations doesn't have contributions chart we cannot handle them. We need a validation.

**Comment by gabrielsch** [comment]
what about checking `itemtype`? 

![image](https://cloud.githubusercontent.com/assets/1733354/23051589/5d5576c0-f4b1-11e6-9f24-6ff4be1798d1.png)

XPath: `//*[@id="js-pjax-container"]/div`

**Comment by CentaurWarchief** [comment]
Great idea. We have two possible types at this point: `itemtype="http://schema.org/Person"` and `itemtype="http://schema.org/Organization"`
